import type { NextPage } from 'next'
import Head from 'next/head'
import ConnectButton from '../components/ConnectButton'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LabDAO Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Lab.
        </h1>

        <p className={styles.description}>
          Open tools accelerate progress.
        </p>

        <ConnectButton />
      </main>

    </div>
  )
}

export default Home
